
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
  name: isaac-build-cache
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi